apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.efs.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.efs.storageSize }}
