replicaCount: 1

image:
  repository: 730335280129.dkr.ecr.us-east-1.amazonaws.com/worker-ecr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  REDIS_HOST: 10.0.140.138
  POSTGRES_HOST: 10.0.139.153
  DB_NAME: mydb
  DB_USER: myuser
  DB_PASSWORD: mypassword

efs:
  server: fs-0e1437fd22b2eef09.efs.us-east-1.amazonaws.com
  path: /worker-data

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
