replicaCount: 1

image:
  repository: 730335280129.dkr.ecr.us-east-1.amazonaws.com/worker-ecr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  REDIS_HOST: 10.0.140.138
  POSTGRES_HOST: 10.0.139.153
  DB_NAME: mydb
  DB_USER: myuser
  DB_PASSWORD: mypassword

efs:
  fileSystemId: fs-0e1437fd22b2eef09  # Replace with your EFS File System ID
  accessPointId: fs-0e1437fd22b2eef09  # Replace with the new Access Point ID for worker-service
  storageClassName: efs-sc
  storageSize: 5Gi
  mountPath: /worker/data  # Adjust as per your application's requirement

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
